### ISSUE TITLE
enhanced workspace shadow copy

### ISSUE THREAD

**Issue by cboudereau** [pchalamet/full-build#42]
Shadow copy not work correctly with ncrunch. targets refer to binaries into bin fullbuild folder. The shadow copy task not work.

Temporary workaround : configure ncrunch to copy fullbuild workspace everytime. But this workaround increase the unit test time processing

**Comment by pchalamet** [comment]
Could you add the aforementioned workaround in the FAQ as this is a limitation of ncrunch ?
https://github.com/pchalamet/full-build/wiki/FAQ

Thanks.
